### ISSUE TITLE
Wordpress Issue 403 - Forbidden. Your domain is probably not allowed on Codapi.

### ISSUE THREAD

**Issue by SQLShortReads** [nalgeon/codapi-js#15]
When attempting to embed within my WordPress site (sqlshortreads.com), I receive the following error:
403 - Forbidden. Your domain is probably not allowed on Codapi.

See the image below.

![image](https://github.com/nalgeon/codapi-js/assets/41455335/c6e98632-98bb-436a-ba46-4f8453e71562)

**Comment by nalgeon** [comment]
The Codapi cloud is in private beta. I think you've never applied, hence the "403 Forbidden" error. Now I've enabled your domain, so the snippets should work.

If you don't want to depend on the Codapi cloud, you can use [in-browser playgrounds](https://github.com/nalgeon/codapi-js#in-browser-playgrounds).

**Comment by SQLShortReads** [comment]
Thank you.

I haven't been able to get the PostgreSQL in-browser playground to work with WordPress. Keep in mind, this could entirely be user error but I've simply pasted what was provided in the example code. If I switch up the order of the scripts, then I get no result.

![image](https://github.com/nalgeon/codapi-js/assets/41455335/a9abf885-1688-4c1b-aa17-07e917577505)

![image](https://github.com/nalgeon/codapi-js/assets/41455335/ff5876da-63d3-4963-a1d8-394d8db978c2)
