### ISSUE TITLE
Possible to delay snippet so Monaco can load first?

### ISSUE THREAD

**Issue by joelburton** [nalgeon/codapi-js#16]
Trying to use an external editor (Monaco, in this case) and it only constructs its full DOM after it initializes (as many in-browser editors do).

However, the Codapi-snippet element needs the selector for the editor's content area and that runs *before* Monaco has made the content area. (I could give it the selector to the editor-itself, but that is very fragile, since line-number and other editor chrome would be in the innerText of the editor)

Is there a way to delay finding the element for an external editor?

**Comment by nalgeon** [comment]
I am closing this because I have not heard from you.
