### ISSUE TITLE
What does the files attribute do in a JavaScript sandbox?

### ISSUE THREAD

**Issue by Danny-Engelman** [nalgeon/codapi-js#17]
I have something like:

```
<script id="inline" type="text/plain">
    console.log("running inline script");
</script>

<codapi-snippet engine="browser" editor="basic" sandbox="javascript" output-mode="dom" files="#inline" >
</codapi-snippet>
```

is ``files="#inline"`` supposed to run the script inside that tag? Thta ``console`` is not executed

Additional question: I presume this does ``document.querySelector("#inline")``
can this be a Web Component shadowDOM reference?

**Comment by nalgeon** [comment]
`files` are only supported by the `codapi` engine.

> can this be a Web Component shadowDOM reference

Nope.
