### ISSUE TITLE
The default timeout time of 10 seconds is too short. How to customize the timeout time?

### ISSUE THREAD

**Issue by jaronnie** [nalgeon/codapi-js#19]
Compiling go program takes more than 10s, got request failed.

**Comment by jaronnie** [comment]
Just a hello demo. Maybe my server configuration is not very good?

<img width="903" alt="iShot_2024-04-03_17 57 45" src="https://github.com/nalgeon/codapi-js/assets/77253497/326bcea2-504a-4e85-88d4-7adac4d0b487">

**Comment by nalgeon** [comment]
Yeah, probably. Compiling Go code in Docker is a bit tricky: you need to prebuild the cache when building an image, otherwise the compilation will be very slow.

Here is a sample Dockerfile that prebuilds the cache for some stdlib packages:

```Dockerfile
FROM golang:1.22-bookworm

RUN adduser --home /sandbox --disabled-password sandbox

USER sandbox
WORKDIR /sandbox/src

COPY --chown=sandbox main.go /sandbox/src
RUN go run main.go
RUN rm -f main.go
```

And a sample `main.go`:

```go
package main

import (
	_ "fmt"
	_ "io"
)

func main() {}
```

**Comment by jaronnie** [comment]
Thank you, I'll give it a try.
