### ISSUE TITLE
unknown engine: wasi

### ISSUE THREAD

**Issue by dogweather** [nalgeon/codapi-js#20]
Hi,

I just gave codapi a try, loading it from the CDN (copy & pasted from the docs):

```html
<script src="https://unpkg.com/@antonz/codapi@0.19.0/dist/snippet.js"></script>
```

I'm using the snippet from the docs:

```html
<codapi-snippet engine="wasi" sandbox="python" editor="basic"></codapi-snippet>
```

but I get this error:

```
unknown engine: wasi
```

Thanks!

**Comment by nalgeon** [comment]
Hi! Please follow the [docs](https://github.com/nalgeon/codapi-js/blob/main/docs/browser-only.md):

Note that WASI-based playgrounds (`engine` = `wasi` in the examples below) require two additional scripts besides the usual `snippet.js`:

```html
<script src="https://unpkg.com/@antonz/runno@0.6.1/dist/runno.js"></script>
<script src="https://unpkg.com/@antonz/codapi@0.19.0/dist/engine/wasi.js"></script>
<script src="https://unpkg.com/@antonz/codapi@0.19.0/dist/snippet.js"></script>
```

**Comment by dogweather** [comment]
Ah hah! Thanks!

**Comment by dogweather** [comment]
Works.
