### ISSUE TITLE
docusaurus no longer plays nice with basic editor and newlines

### ISSUE THREAD

**Issue by srenatus** [nalgeon/codapi-js#22]
Hi!

I've been banging my head against using codapi-js with docusaurus. If you see [this very basic demonstration on codesandbox.io](https://codesandbox.io/p/devbox/dreamy-darkness-q2zvnc?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clv578ekj00082e68qmp84k93%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clv578ekj00032e68s3liqdt3%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clv578ekj00052e68h6jtad6t%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clv578ekj00072e68snm9h71h%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clv578ekj00032e68s3liqdt3%2522%253A%257B%2522id%2522%253A%2522clv578ekj00032e68s3liqdt3%2522%252C%2522activeTabId%2522%253A%2522clv57je1q00os2e68hpm2e1tr%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clv578ekj00022e68ng6dkxlo%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clv579azt004r2e684bi6amat%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fdocusaurus.config.ts%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522clv57je1q00os2e68hpm2e1tr%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clv578ekj00072e68snm9h71h%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clv578ekj00062e68cw2lyznt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252Fblog%252Fcodapi%2522%257D%255D%252C%2522id%2522%253A%2522clv578ekj00072e68snm9h71h%2522%252C%2522activeTabId%2522%253A%2522clv578ekj00062e68cw2lyznt%2522%257D%252C%2522clv578ekj00052e68h6jtad6t%2522%253A%257B%2522id%2522%253A%2522clv578ekj00052e68h6jtad6t%2522%252C%2522activeTabId%2522%253A%2522clv578ekj00042e68qyz29y1v%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clv578ekj00042e68qyz29y1v%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clv57d2ea00162e689710c7ya%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clv57d2hv0a3zdheh7ggl0sk6%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D), and you "browse" to `/blog/codapi` in the embedded browser, you'll find this:

<img width="368" alt="image" src="https://github.com/nalgeon/codapi-js/assets/870638/e30246a0-6396-4d85-ab0d-b6458b7a0cfa">

⏬ Clicking on "edit", or clicking into the highlighted code, makes it become this:

<img width="487" alt="image" src="https://github.com/nalgeon/codapi-js/assets/870638/a273011c-b5a3-4b16-a067-d8219ed44d04">

(I'm aware that it's not set up to actually _Run_ anything, but that's OK, I'm merely worried about the basic editor right now.)

Googling around, I wasn't able to find much; maybe https://github.com/PrismJS/prism/issues/1764 could be related, or maybe not.

Short of using Codejar instead, do you happen to have an idea how this could be made to work?currently 

Related to https://github.com/nalgeon/codapi-js/commit/9eb1ea3af21df83fee7716e711d5c5932eb3b736, I believe, since [this ferretdb blog post](https://blog.ferretdb.io/mongodb-crud-operations-with-ferretdb/) works fine, and uses the previous code (not the textcontent approach)

Thanks for your time 😃

**Comment by nalgeon** [comment]
Oh boy. I just _love_ Docusaurus. Please see if 0.19.4 fixes the problem for you.

**Comment by srenatus** [comment]
Oh this is a bit of a riddle. Turns out that when I put
````
<pre id="policy.rego"><code>
package authz
import rego.v1
default allow := false
allow if input.subject == "alice"
</code></pre>
````

in the code, it works (with newlines where they should be), but if I put
````
<pre id="policy.rego"><code>
package authz
import rego.v1

default allow := false
allow if input.subject == "alice"
</code></pre>
````
in (with a logical separation), the request sent on the wire is
```json
{
  "sandbox": "opa-ts",
  "version": "",
  "command": "run",
  "files": {
    "": "...not important...",
    "policy.rego": "package authz\nimport rego.v1default allow := false\nallow if input.subject == \"alice\"",
  }
}
```

...so it's missing the newline here:
```
import rego.v1default allow := false\n
             ^^
```

Do you have any idea what could be going on here?

**Comment by nalgeon** [comment]
> It's all going well when referencing `script` tags, but it fails for `codapi-snippet`

Fixed in 0.19.5.

> Turns out that when I put `pre`...

Please don't use `pre`s for files. Only one of the following: a) external files, b) `script`s or c) `codapi-snippet`s.

**Comment by srenatus** [comment]
Thanks again!

**Comment by srenatus** [comment]
Thanks again!
