### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by gotohuman** [nalgeon/codapi-js#27]
I'm using the fetch sandbox from my docusaurus docs. But the api request I trigger gets blocked by CORS. The same call works without any issues from a Google Colab or Postman, so wondering if this is a codapi issue?!

**Comment by nalgeon** [comment]
It's not a Codapi issue. It means that the resource you are trying to access does not allow [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) (cross-domain requests from the browser).
