### ISSUE TITLE
When JavaScript syntax isn't valid error is misleading

### ISSUE THREAD

**Issue by buckett** [nalgeon/codapi-js#3]
If I enter some some code of:
```javascript
for(
```
Then when it runs in the browser JavaScript playground I get:
```
SyntaxError: Unexpected token '}'
```
which is confusing because there isn't a `}` in the code that I've entered (I'm not using a template). If I `eval` the same code:
```javascript
eval("for(")
```
 I get:
```
VM41831:1 Uncaught SyntaxError: Unexpected end of input
    at <anonymous>:1:1
```
which is what I was expecting to see.

**Comment by nalgeon** [comment]
This is how `AsyncFunction` works. I don't see any way to do a better syntax check. `eval` messes with global scope and is not suitable for async, so I don't think it's the way to go.
