### ISSUE TITLE
raw string with console.log("codapi") fails execution because appendChild is used

### ISSUE THREAD

**Issue by Danny-Engelman** [nalgeon/codapi-js#30]
```
<pre>
        console.log("codapi");
</pre>
<codapi-snippet engine="browser" sandbox="javascript" output-mode="dom"></codapi-snippet>
```

fails execution 

![](https://i.imgur.com/Y5f80MT.png)

because in ``showResult``codapi code:

![](https://i.imgur.com/kcXq7yk.png)

parameter e is the raw string ``"codapi"``,  and appendChild only accepts nodes

I think its save to replace ``appendChild``  with ``append`` (wasn't available in IE11) as ``append`` accepts (HTML)strings AND nodes

**Comment by nalgeon** [comment]
It fails because the `dom` output mode expects the user code to return a DOM node. What's wrong with that?

**Comment by Danny-Engelman** [comment]
Text Nodes **_are_** DOM nodes

AppendChild doesn't accept Text Nodes

Append does

**Comment by nalgeon** [comment]
Text nodes are DOM nodes. `appendChild` accept text nodes. Your code does not return a text node (or any `Node` for that matter).

**Comment by Danny-Engelman** [comment]
the parameter for showResult is:

![](https://github.com/nalgeon/codapi-js/assets/3382713/2d3bd8e3-da9d-40f1-9ff8-e9651036d1f8)

appendChild wants to output 'codapi'

**Comment by nalgeon** [comment]
Sorry, I'm lost here.

The `dom` output mode expects user code to return a DOM node (not a string). Do not use the `dom` mode if your code returns anything other than DOM nodes — you'll get an error.

Closing.

**Comment by Danny-Engelman** [comment]
Basically **codapi** can not handle ``console.log`` statements properly

https://jsfiddle.net/WebComponents/ay0dkcrt/

Won't execute properly because it errors on ``appendChild``

Simply fixed by replacing ``appendChild`` with ``append``
