### ISSUE TITLE
sqlite file template loading problem 

### ISSUE THREAD

**Issue by khlsvr** [nalgeon/codapi-js#31]
I am trying out the sqlite playground with the basic example. I am modifying it to load a template sql. All works well with in-page script, but when I try load it from a file I just get "ok" in the query result. I picked up a demo table from sqlime.org's project page. Here are the contents of the html files of these two approaches:

in-page - works:

```html
<script src="https://unpkg.com/@antonz/runno@0.6.1/dist/runno.js"></script>
<script src="https://unpkg.com/@antonz/codapi@0.19.0/dist/engine/wasi.js"></script>
<script src="https://unpkg.com/@antonz/codapi@0.19.0/dist/snippet.js"></script>

<script id="demo.sql" type="text/plain">

PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE employees (
    id integer primary key,
    name text,
    city text,
    department text,
    salary integer
);
INSERT INTO employees VALUES(11,'Diane','London','hr',70);
INSERT INTO employees VALUES(12,'Bob','London','hr',78);
INSERT INTO employees VALUES(21,'Emma','London','it',84);
INSERT INTO employees VALUES(22,'Grace','Berlin','it',90);
INSERT INTO employees VALUES(23,'Henry','London','it',104);
INSERT INTO employees VALUES(24,'Irene','Berlin','it',104);
INSERT INTO employees VALUES(25,'Frank','Berlin','it',120);
INSERT INTO employees VALUES(31,'Cindy','Berlin','sales',96);
INSERT INTO employees VALUES(32,'Dave','London','sales',96);
INSERT INTO employees VALUES(33,'Alice','Berlin','sales',100);
CREATE TABLE expenses (
    year integer,
    month integer,
    income integer,
    expense integer
);
INSERT INTO expenses VALUES(2020,1,94,82);
INSERT INTO expenses VALUES(2020,2,94,75);
INSERT INTO expenses VALUES(2020,3,94,104);
INSERT INTO expenses VALUES(2020,4,100,94);
INSERT INTO expenses VALUES(2020,5,100,99);
INSERT INTO expenses VALUES(2020,6,100,105);
INSERT INTO expenses VALUES(2020,7,100,95);
INSERT INTO expenses VALUES(2020,8,100,110);
INSERT INTO expenses VALUES(2020,9,104,104);
COMMIT;

##CODE##

</script>

<pre>
select * from employees limit 3;
</pre>

<codapi-snippet engine=wasi sandbox=sqlite editor=basic template=#demo.sql actions=Fullscreen:@fullscreen></codapi-snippet>

```

Template from a file demo.sql located in the same dir as the html file and which has the exact content that is in the in-page script above. The demo.sql was given -rw-r--r-- permissions.  Produces only "ok" when query being run. Browser's console has no output:

```html
<script src="https://unpkg.com/@antonz/runno@0.6.1/dist/runno.js"></script>
<script src="https://unpkg.com/@antonz/codapi@0.19.0/dist/engine/wasi.js"></script>
<script src="https://unpkg.com/@antonz/codapi@0.19.0/dist/snippet.js"></script>

<pre>
select * from employees limit 3;
</pre>

<codapi-snippet engine=wasi sandbox=sqlite editor=basic template=demo.sql actions=Fullscreen:@fullscreen></codapi-snippet>

```

**Comment by nalgeon** [comment]
How do you run your web server (which serves the web page and demo.sql)?

**Comment by khlsvr** [comment]
It's on my android phone running termux, which is running nginx. There's cloudflare in the middle which may do something there other than making it accessible to ipv4 world since my phone's internet connection has an ipv6 address. That it is doing at least. There's nothing in nginx's error.log, in the access.log there is a line regarding the sql file after pressing "run"
`; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/6.7.0 Chrome/118.0.5993.220 Safari/537.36"
2400:xxxx:79:1024::<redacted> - - [28/May/2024:14:30:56 +0300] "GET /wc/s/demo.sql HTTP/1.1" 304 0 "http://<redacted>.org:8080/wc/s/test.html" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/6.7.0 Chrome/118.0.5993.220 Safari/537.36"`

 My phone's web server won't be the end location. Maybe I should try on github pages if it would work there then if nothing is wrong on my end with the html file etc. I wonder if I could find out whether it would work on github pages without first going all the steps of creating a project with github pages and going through all that

**Comment by nalgeon** [comment]
Your file setup works for me. Are you sure you have the `##CODE##` line at the and of the `demo.sql` file?

**Comment by khlsvr** [comment]
Thanks that was it :blush:   Nice job finding where I might have the problem :)
