### ISSUE TITLE
Error when editing in HTML mode

### ISSUE THREAD

**Issue by bitFez** [nalgeon/codapi-js#33]
I seem to be getting an error in HTML mode once I click to edit a Python Snippet and it adds a new line.

In the example below, I add a line above the `msg` variable in order to assign the `name` variable.
![image](https://github.com/nalgeon/codapi-js/assets/5003973/d326f297-d8fd-4619-ad92-548647afb0b3)

This is my current HTML code:
```html
<pre>
msg = f"Hello, {name}!"
print(msg)
</pre>

<codapi-snippet engine="wasi" sandbox="python" editor="basic"></codapi-snippet>
``` 

For context, I am using the following files all loaded in the order shown below and they are loading from my own directories and not via cdn.
- runno.js
- wasi.js
- snippet.js
- snippet.css

**Comment by bitFez** [comment]
It was the latest 0.19.7

**Comment by nalgeon** [comment]
I see. Instead of this:

```html
<pre>
msg = f"Hello, {name}!"
print(msg)
</pre>
```

Use this:

```html
<pre><code>
msg = f"Hello, {name}!"
print(msg)
</code></pre>
```

[Live demo](https://codepen.io/ohmypy/pen/jOooBGp)

I'll update the examples.

**Comment by bitFez** [comment]
Thank you this worked!
