### ISSUE TITLE
Disable spellcheck in editable components?

### ISSUE THREAD

**Issue by stefanvanburen** [nalgeon/codapi-js#34]
e.g. on https://antonz.org/sql-window-functions-ranking/#multiple-windows, I see:

<img width="875" alt="image" src="https://github.com/user-attachments/assets/6da19711-0483-4aff-92bf-0105ff7e21c0">

Which I believe is from the editor?: https://github.com/nalgeon/codapi-js/blob/main/src/editor.js#L40

I suspect a simple [`spellcheck="false"`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/spellcheck) would do the trick, but wanted to check if you thought that was reasonable behavior.

**Comment by nalgeon** [comment]
Makes sense, thank you. I'll disable spell checking.
