### ISSUE TITLE
Python modules in sandbox

### ISSUE THREAD

**Issue by p3k** [nalgeon/codapi-js#35]
I am trying out Codapi as a documentation tool for our RESTful API – I like it very much, congrats on this project and its implementation!
:relaxed: 

Is there any information available which Python modules are available in the sandbox when using the WASI engine?

I tried to import `requests` and `urllib3`, but both give me the same “ModuleNotFoundError”…

Is there a way to provide a Python sandbox demonstrating an HTTP request in Codapi?

**Comment by nalgeon** [comment]
Hi Toby, thanks for trying Codapi! There are only stdlib modules available in the Python WASI sandbox. Also, the network doesn't work, so no HTTP requests at all.

You can set up your own Codapi server with a Python sandbox and enable networking there if you'd like.

**Comment by p3k** [comment]
I see. Would that involve [adding a sandbox](https://github.com/nalgeon/codapi/blob/main/docs/add-sandbox.md) and then adding the desired modules in requirements.txt? Or how would I enable networking?

Are there any security implications of enabling networking in Codapi?

**Comment by nalgeon** [comment]
That would involve adding a sandbox, installing all the necessary packages (like requests) and enabling external networking in Docker. With all the possible consequences of enabling networking in Docker.

**Comment by p3k** [comment]
OK, makes sense. 

Wouldn’t it be safer to provide (one of) the HTTP libraries in the WASI engine, then? I read that [urllib3 is available in pyodide](https://urllib3.readthedocs.io/en/stable/reference/contrib/emscripten.html) – but I know too little about web assembly to make anything out of this information…

Is there a way to load e.g. the requests module in a `<script>` element, similar to how runno.js and wasi.js are loaded?

**Comment by nalgeon** [comment]
Network requests may work with Pyodide, but I haven't tried it (and Pyodide is not yet available as a Codapi engine).

> Is there a way to load e.g. the requests module in a <script> element, similar to how runno.js and wasi.js are loaded?

Nope.

**Comment by p3k** [comment]
OK, thanks for the support.

I added a Python sandbox following the documentation, added the requests module in requirements.txt, and enabled networking by setting the corresponding property in configs/config.json. Works great!

**Comment by nalgeon** [comment]
Glad to hear everything went smoothly! I'll probably try adding Pyodide later and let you know if it becomes a viable option.
