### ISSUE TITLE
CORS error is shown as general network error

### ISSUE THREAD

**Issue by buckett** [nalgeon/codapi-js#4]
When I attempt to use codapi.org from an origin that isn't allowed I get:
```
Either Codapi is down or there is a network problem.
(TypeError: Failed to fetch)
```
I get exactly the same error if I block the exec URL using Chrome's "Network request blocking".

I'm not sure there is any way to detect that the request failed because CORS doesn't allow the domain the request is made from, but it might be useful to have `networkErrMsg` mention that the origin might not have been enabled.

Until you get past CORS you won't get the HTTP 403 error back.

**Comment by nalgeon** [comment]
Fixed on the server by adding CORS headers to 403 responses.
