### ISSUE TITLE
Support for python execution directly from browser

### ISSUE THREAD

**Issue by sudharsan-selvaraj** [nalgeon/codapi-js#8]
First of all i would like to appreciate for bringing up the great idea to lights. I really like the idea and would like to propose a feature which enables the users to run python scripts directly from the browser similar to [jupyter](https://github.com/jupyter/)

With the help of [Pyodide](https://pyodide.org/en/stable/usage/index.html), we can now run any python scripts directly from the browser and  It doesn't stop there. It also provide us with a capability to install any pip modules and use the same in the script. i already made the integration of pydiode to codapi-js and attaching the screenshots of its capability. If you think this feature can be integrated, i'm will open PR and you can review the changes. Give it a shot and let me know you thoughts.

Attaching few sample screenshots:

**using matplotlib:**
<img width="1728" alt="Screenshot 2023-12-27 at 11 16 59 PM" src="https://github.com/nalgeon/codapi-js/assets/20136913/e8eb0b25-5c8e-4074-8a9b-39f9074db3b4">

**using pandas module:**
<img width="1728" alt="Screenshot 2023-12-27 at 11 19 55 PM" src="https://github.com/nalgeon/codapi-js/assets/20136913/7e3064c9-e88d-426b-9422-2aa041b5242a">

**Comment by nalgeon** [comment]
Sudharsan, thank you so much for building this Pyodide-powered engine! (I checked out your repo).

In principle, I like the idea of implementing more client-side sandboxes like yours. I'm not sure about the design though, so I'd like to think about it for a while. A PR would be a bit premature at this point.

In any case, when I decide on the best way to integrate client-side engines, I'll give you appropriate credit as the author of the Python implementation.

Thanks again!

**Comment by sudharsan-selvaraj** [comment]
Sure, sounds goods!
