### ISSUE TITLE
Change URLs for wasm artifacts

### ISSUE THREAD

**Issue by muellerj** [nalgeon/codapi-js#9]
First of all thanks for the amazing work you've done here!

I would like to run a workbook from a self-contained network, where access to `unpkg` etc. is not viable. To that extent, the sources for the `*.wasm` artifacts are currently hard-coded in `src/engine/wasi/boxes.js`. I can of course edit these in place after caching them locally, but I think it would be nice to be able to configure them in some way. 

The provided locations on `unpkg` could serve as sensible defaults if no customisation is wanted/needed.

**Comment by muellerj** [comment]
Awesome, that was very fast :)

This works just as intended, please feel free to close this issue. Thank you very much!

**Comment by nalgeon** [comment]
Thanks for suggesting it!
